name:                mud-drifter
version:             0.1.0.0
github:              "tort/mud-drifter"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/proj#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: [ protolude
                , text
                , text-show
                , bytestring 
                , word8
                , containers
                , binary
                , async
                , safe-exceptions
                , fgl
                , directory
                , timers
                , suspend
                , network-simple
                , network
                , parsec
                , attoparsec
                , MissingH
                , lens
                , pipes
                , pipes-binary
                , pipes-network
                , pipes-parse
                , pipes-attoparsec
                , pipes-bytestring
                , pipes-concurrency 
                , time
                , regex-tdfa
                , mtl
                ]

executables:
  mud-drifter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: [ mud-drifter
                  , text
                  , protolude
                  , bytestring
                  , suspend
                  , timers
                  , pipes
                  , pipes-network
                  , directory
                  , pipes-concurrency ]

tests:
  drifter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: [ mud-drifter 
                  , protolude
                  , hspec
                  , hspec-attoparsec
                  , QuickCheck
                  , quickcheck-instances
                  , pipes
                  , pipes-bytestring
                  , text
                  , text-show
                  , bytestring
                  , fgl
                  , containers
                  , parsec ]
